name: Build Mobile App APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Stable Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Java 17 Engine
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python Package Utilities
        run: |
          pip install --upgrade pip==24.0
          pip install buildozer cython virtualenv

      - name: Configure Android SDK Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Compile Game to APK
        run: |
          buildozer init
          sed -i 's/orientation = portrait/orientation = landscape/g' buildozer.spec
          buildozer -v android debug

      - name: Save Mobile App File
        uses: actions/upload-artifact@v4
        with:
          name: mobile-game-apk
          path: bin/*.apk
